#!/usr/bin/env bash
# install nginx on my server ubuntu@54.165.55.51

sudo apt update
sudo apt upgrade -y

sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
