#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom header configuration to Nginx
sudo sed -i '/^http {/a \    server_tokens off;\n    add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx

# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

