#!/usr/bin/env bash
# Bash script to install and configure HAproxy on lb-01 server

# Update package list
apt-get -y update

# Install HAproxy
apt-get -y install haproxy

# Configure HAproxy
cat <<EOF >/etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Enable HAproxy to be managed via init script
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy to apply changes
service haproxy restart

