#!/usr/bin/env bash
#Script to make configuration of nginx to listen to port 80 sweet and short
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
